eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#feign默认关闭，需要手动开启断路器
feign:
  hystrix:
    enabled: true

server:
  port: 8766
spring:
  application:
    name: hystrix-ribbon